modify mkdist to use internal source
git-svn-id: svn://svn.rforge.net/iplots/trunk@136 8e282063-7124-4b67-9d11-cc4721fc7695

diff --git a/mkdist b/mkdist
--- a/mkdist
+++ b/mkdist
@@ -2,104 +2,57 @@
 
 : ${JFLAGS=-target 1.4 -source 1.4}
 
+PNAME=iplots
 SWD=`pwd`
 echo "Removing previous dist ..."
-rm -rf /tmp/iplots
+rm -rf /tmp/${PNAME}
 echo "Copying package base ..."
-cp -r ../iplots /tmp
+cp -r . /tmp/${PNAME}
 
-rm -rf /tmp/iplots.java
-mkdir /tmp/iplots.java
-
-JARFILE=$1
-
-if [ -z "$JARFILE" ]; then
-    if [ -z "${ORGPATH}" ]; then
-	DEFAULTSRC="${SWD}/../../../org";
-    else
-	DEFAULTSRC="${ORGPATH}"
-    fi
-    JARFILE="${DEFAULTSRC}/iplots.jar";
-    rm -f "$JARFILE"
-    make -C "${DEFAULTSRC}" iplots.jar
-    cd "${SWD}"
-fi
-if [ ! -e "$JARFILE" ]; then
-    echo "*** ERROR: cannot find iplots.jar in $JARFILE" >&2
-    echo "Please check out org/rosuda or set JARFILE correspondingly" >&2
-    exit 2
+if [ ! -e "/tmp/${PNAME}/java/org/Makefile" ]; then
+    echo "*** ERROR: cannot find Java sources"
+    exit 1
 fi
 
-#echo "Copying sources ..."
-#if [ ! -e ../../../org/rosuda/iplots/Framework.java ]; then
-#   echo "Can't find sources! Check out both R and org/rosuda modules!"
-#   exit 1
-#fi
-#find ../../../org/rosuda name \*.java -exec cp \{\} /tmp/iplots.java/ \;
-
-#cp ../../../java/stat/klimt/src/*.java /tmp/iplots.java
-
-cp "${DEFAULTSRC}/rosuda/iplots/iPlots.jpg" /tmp/iplots.java/iPlots.jpg
-cp "${DEFAULTSRC}/rosuda/ibase/Common.java" /tmp/iplots.java/Common.java
-
-# we need an absolute path because we're running in /tmp
-JBASE=`dirname $JARFILE`
-JNAME=`basename $JARFILE`
-cd $JBASE
-JARFILE=`pwd`/$JNAME
-
-cd /tmp/iplots.java
-jar fx ${JARFILE}
-mv iPlots.jpg splash.jpg
-
-rm /tmp/iplots/mkdist
-
-cd /tmp/iplots
+cd /tmp/${PNAME}
 VER=`awk -v ORS= '/Package version:/ { print $4 }' R/iplots.R`
 echo "iplots version ${VER}"
 
-cd /tmp/iplots.java
-#echo Removing plugins and wrappers ...
-#rm -f PluginDeriveVar.java PluginGetTreeR.java PluginStartRserve.java PoGraSSSVG.java tfw.java Wrapper.java StaticReader.java PGSviewer.java
-
 # adjust version number
-echo "Adjust version number and re-compile Common.java ..."
-cat Common.java | sed "s/Version=\"[0-9]*.[0-9]*\"/Version=\"${VER}\"/" > c
-rm Common.java
-mv c org/rosuda/ibase/Common.java
-echo "javac $JFLAGS -d . -classpath . org/rosuda/ibase/Common.java"
-javac $JFLAGS -d . -classpath . org/rosuda/ibase/Common.java
-rm -f org/rosuda/ibase/Common.java
-if [ ! -e org/rosuda/ibase/Common.class ]; then
-  echo "*** ERROR: cannot compile Common.class ***"
-  echo "*** ERROR: cannot compile Common.class ***" >&2
-  exit 1
+echo "Adjust version number ..."
+cat java/org/rosuda/ibase/Common.java | sed "s/Version=\"[0-9]*.[0-9]*\"/Version=\"${VER}\"/" > java/org/rosuda/ibase/Common.java.tmp && mv java/org/rosuda/ibase/Common.java.tmp java/org/rosuda/ibase/Common.java
+
+echo "Compile Java sources ..."
+make -C java/org iplots.jar
+JARFILE="java/org/iplots.jar"
+if [ ! -e "${JARFILE}" ]; then
+    echo "*** ERROR: unable to compile Java sources"
+    exit 1
 fi
 
-#echo Compiling sources ...
-#javac -O *.java
-echo Creating archive ...
-jar fc iplots.jar org splash.jpg
-
 echo "Copying java archive ..."
-mkdir -p /tmp/iplots/inst/cont
-cp iplots.jar /tmp/iplots/inst/cont
+mkdir -p inst/cont
+cp "${JARFILE}" inst/cont
+ln -s cont inst/java
 
-cd /tmp/iplots
+rm -rf mkdist java 
+
 echo "Removing CVS/SVN and backup stuff ..."
 rm -rf `find . -name CVS -or -name .svn -or -name \*~ -or -name .#\*`
+
 #echo "Updating INDEX ..."
-cd ..
+#cd ..
 #R CMD Rdindex iplots > iplots/INDEX
+#cd iplots
+
 echo "Updating version ..."
-cd iplots
-cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
-mv d DESCRIPTION
+cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d && mv d DESCRIPTION
+
 echo "Creating package ..."
 cd ..
-tar fcz iplots_${VER}.tar.gz iplots
+tar fcz ${PNAME}_${VER}.tar.gz ${PNAME}
 cd ${SWD}
-cp /tmp/iplots_${VER}.tar.gz ..
-rm -rf /tmp/iplots /tmp/iplots.java
+cp /tmp/${PNAME}_${VER}.tar.gz ..
+rm -rf /tmp/${PNAME}
 echo "Done."
-ls -l ../iplots_${VER}.tar.gz
+ls -l ../${PNAME}_${VER}.tar.gz
